### PR TITLE
CLOUD-61198 Fix cloudbreak-shell-remote command

### PR DESCRIPTION
**Pull request by mhmxs**
@akanto plz review

### CODE REVIEW

**Comment by lalyos** [comment]
wouldn't double quotes have the same effect? If we need quotation for env vars, we already use that style, as in https://github.com/sequenceiq/cloudbreak-deployer/commit/61d5e48d07afe489c2b9833c134541171ca2cf02

**Comment by mhmxs** [comment]
With double quotes bash parses characters for example in password. So single one is better. First i putted all the env into quotes, like -e 'ENV=value', but @akanto suggested this form.

**Comment by lalyos** [comment]
But this is all in the middle of a heredoc. So neither single or double quote has no influence about the generated docker-compose.yml. All $VARS will be replaced by the heredoc feature.

So the 2 stags are:
- heredoc produces the docker-compose.yml, which has already $VAR replaced with actual values
- docker-compose will parse the yaml file and start containers

Now, the quotation is taken into account inside of the yaml file. But its a python yaml parser. An according to the docker-compose documentation the correct syntax for array style listing is:
```
    environments:
        - "ENV1=some str@nge string!"
        - ENV2=simple
```

**Comment by lalyos** [comment]
Ohh I see, i thought its inside of the compose file ....

**Pull request merged**
